### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by HilkoLantinga** [wouldgo/twofish#1]
I'm trying to communicate in Node.js with a device that uses Twofish in CBC mode.

I know the frames encrypted and unencrypted and I know that the first 16 bytes of the encrypted frame are the initialization vector, the next two are the length (to exclude the padding) and everything else is the Twofish encrypted message:

``` javascript
var key = new Buffer('01000000000000000000000000000000', 'hex');
var encrypted = new Buffer('b46a0260b0bc4922b5eb0785a4b7cc9e000f1425e4bb3d59f55734af263a60097901', 'hex');
var decoded = new Buffer('5ea08000000106010000000000e81c', 'hex');
```

If I use http://twofish.online-domain-tools.com with:
b4 6a 02 60 b0 bc 49 22 b5 eb 07 85 a4 b7 cc 9e as hex init. vector
14 25 e4 bb 3d 59 f5 57 34 af 26 3a 60 09 79 01 as hex input
01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 as hex key 

I get:
5e a0 80 00 00 01 06 01 00 00 00 00 00 e8 1c 00 as hex output (which makes sense as the length 0f means that the last 00 is just padding).

If I try to use yours then I get:
twofish.js:109
        , nStrLen = sDOMStr.length
                           ^
TypeError: Cannot read property 'length' of undefined
    at Object.strToUTF8Arr [as stringToUTF8Array](/Users/hlantinga/Documents/ATS/twofish.js:109:28)
    at Object.decryptCBC [as decryptCBCMode](/Users/hlantinga/Documents/ATS/twofish.js:920:23)

**Comment by HilkoLantinga** [comment]
One step further, but still not the correct answer:

``` javascript
var twof = require('./twofish');
var twofish = new twof.twoFish([0xb4,0x6a,0x02,0x60,0xb0,0xbc,0x49,0x22,0xb5,0xeb,0x07,0x85,0xa4,0xb7,0xcc,0x9e]);
var key = new Buffer('01000000000000000000000000000000', 'hex');
var test = new Buffer(twofish.decryptCBCMode(key.toString(),[0x14,0x25,0xe4,0xbb,0x3d,0x59,0xf5,0x57,0x34,0xaf,0x26,0x3a,0x60,0x09,0x79,0x01]));
util.log(util.inspect(test, false, null, true));
/*
 output:
<Buffer c2 b6 c2 bd e7 9d 91 7a c2 8c 62 70 c2 86 5c 3b 39 1f 45>
 */
```

Maybe it has something todo with the padding? It says 'No padding' in the docs.

**Comment by wouldgo** [comment]
Hi,
probably you're right.

By now I'm in my parents home 500 km far from my developing machine. I'll investigate (reading again the docs) and eventually fix the problem.

If you have some other ideas please let me know.

Thanks.

**Comment by HilkoLantinga** [comment]
Thanks for responding! Anyway I've tried https://github.com/tugrul/node-mcrypt that uses the native mcrypt bindings, that works straight away:

``` javascript
yum install libmcrypt-devel
npm install mcrypt

/*jslint node: true*/
var MCrypt = require('mcrypt').MCrypt,
    twofish = new MCrypt('twofish', 'cbc'),
    key = new Buffer('01000000000000000000000000000000', 'hex'),
    assert = require('assert');

var decrypt = function(frame, key) {'use strict';
    //use first 16 bytes as Initialization Vector:
    twofish.open(key, frame.slice(0, 16));
    //decrypt from byte 18 and then return the slice using the length in byte 16 and 17:
    return twofish.decrypt(frame.slice(18)).slice(0, frame.readUInt16BE(16));
};

var encrypt = function(frame, key) {'use strict';
    var padded,
        ret,
        enc,
        iv = twofish.generateIv();
    twofish.open(key, iv);
    //pad frame with zeros until you can divide it with 16:
    padded = new Buffer(Math.ceil(frame.length / 16) * 16);
    padded.fill(0);
    frame.copy(padded);
    //encrypt padded:
    enc = twofish.encrypt(padded);
    //set ret to new length and copy Initialization Vector:
    ret = new Buffer(2 + iv.length + padded.length);
    iv.copy(ret);
    //add high and low byte with true length (length without extra zeros):
    ret.writeUInt16BE(frame.length, iv.length);
    //add encrypted part and return:
    enc.copy(ret, iv.length + 2);
    return ret;
};

var test1 = decrypt(new Buffer('b46a0260b0bc4922b5eb0785a4b7cc9e000f1425e4bb3d59f55734af263a60097901', 'hex'), key);
var test2 = encrypt(new Buffer('5ea08000000106010000000000e81c', 'hex'), key);
var test3 = decrypt(test2, key);
var test4 = encrypt(new Buffer('5ea08000000106010000000000e81c', 'hex'), key);

console.log(test1.toString('hex'));//5ea08000000106010000000000e81c
console.log(test2.toString('hex'));//37b780791987bec9764668dd9eabb64f000fa9522a2f37185d891d95355a13db1977 different every time
console.log(test3.toString('hex'));//5ea08000000106010000000000e81c
console.log(test4.toString('hex'));//a6cbd27013a4e9e640aabc7cd1cf6cc2000fa7d3d102c3c13d6db8c3a27bc07e4115 different every time

assert.deepEqual(test1, new Buffer('5ea08000000106010000000000e81c', 'hex'), 'Test 1 should be 5ea08000000106010000000000e81c!');
assert.deepEqual(test1, test3, 'Test 1 and 3 should be equal!');
assert.notDeepEqual(test2, test4, 'Test 2 and 4 should not be equal!');
console.log('\u001B[32mAll tests where ok!\u001B[0m');
```

Unfortunately I can't use mcrypt bindings as it only works with node 0.10.x and only on some Linux distro's. The readme of mcrypt has an interesting remark:
_Alright! There is already OpenSSL extension bundled with Node.js but there are something wrong with some traditional encryption algorithms on OpenSSL._

_I tried to decrypt ciphertext of AES and DES algorithms using OpenSSL but i get the garbage outputs. There are some reasons with OpenSSL like null padding._

_Also i saw same issues on the stackoverflow.com. Some people encountered with same problems._

_This extension provide the cipher and decipher operations via libmcrypt and compatible with Java Crypto and PHP MCrypt consequently._

What I also found is this: https://gist.github.com/pradipchitrakar/7371118
That basically shows how to get around the issue (with AES), don't use any padding when decrypting or encrypting in nodejs, because the unencrypted message is padded to the correct length. Now how could we add CBCnoPadding functions in your code or add a parameter for the padding mode (including 'noPadding')?
I think some of the other options from mcrypt would also be nice, like generating an iv and also support buffers.

**Comment by wouldgo** [comment]
Sorry @HilkoLantinga, but coming back from Christmas holidays brings me in a "clients issues spiral of death"...

Today, after working time, I'll review the issue much more carefully.

**Comment by HilkoLantinga** [comment]
Don't be sorry. It's great that you're willing to take a look in the first place.

**Comment by wouldgo** [comment]
So,

I haven't a solution by now but I tried to understand from your comments the scenario:
[Here](https://github.com/wouldgo/twofish/blob/master/spec/2-fish-CBC%20-%20issues.js#L25) I tried to wrote down a test.
The ciphertext has to be an array, so I've ported all the values: are these right? If yes the outcome from decryption is different from what you have reported.
I've tried to trace the steps and all seems right. If you see any issues in the test case (I hope so :pray:) or you spot some of my mistakes please let me know...

Thanks.

**Comment by HilkoLantinga** [comment]
The numbers you using are spot on. IV is correct, Key is correct, Expected output is correct.

**Comment by wouldgo** [comment]
I again @HilkoLantinga,

I reviewed the entire algorithm spotting some issues around typed arrays usage. Now the implementation seems good.
Could you please test again in your scenario? If the outcome will be correct I would release a new version in npm.
Thank you
Dario

**Comment by HilkoLantinga** [comment]
Unfortunately I'm in a hotel that does not allow VPN so I can't check it against the device, will be home in 2 days and test it.

**Comment by wouldgo** [comment]
No problem man,

I'll write down the other tests scenarios from literature.

**Comment by wouldgo** [comment]
Right now, testing against cbc-d-m datas, I think the actual version has some problems...

**Comment by wouldgo** [comment]
Ok.

now [here](https://github.com/wouldgo/twofish/blob/master/spec/cbc-issue-1.js) you can find the spec that refers to your issue, it passes.

**Comment by wouldgo** [comment]
tagged version [1.0.0](https://github.com/wouldgo/twofish/tree/1.0.0) version is now on npm.
If you encounter future problems let me know here or in another issue.

Thanks for your contribution.
