### ISSUE TITLE
Usage with nodejs

### ISSUE THREAD

**Issue by Extarys** [wouldgo/twofish#3]
Hi there,

Could you please provide some baseic example with NodeJS?

This is the only library and I would love to use Twofish in my new project.

Thank you so much <3

**Comment by wouldgo** [comment]
Hi,
here is a simple example:
```js
const {twofish} = require('twofish')
  , crypt = twofish()
  , key = crypt.stringToByteArray('a-secret-key')
  , pt = crypt.stringToByteArray('☭☢€  ☂ ڴ Super secret message!')
  , ct = crypt.encrypt(key, pt)
  , cpt = crypt.decrypt(key, ct)
  , compare = (first, second) => {
    if (first.length != second.length) {

      return false
    }
    for (let i = 0; i < second.length; i++) {
      if (!compare(first[i], second[i])) {

        return false;
      } else if (first[i] !== second[i]) {

        return false
      }
    }
    return true;
};

console.info('Is plaintext equals to result of chiphertext decryption:', compare(pt, cpt), 
  'chipher text decrypted:', crypt.byteArrayToString(cpt));
```

It's possible to review each use case looking at the [spec](https://github.com/wouldgo/twofish/tree/master/spec) folder.
Feel free to reopen if there are some issues.

Have a great day,
Dario.

**Comment by Extarys** [comment]
You are awesome, thank you very much <3

**Comment by mnpenner** [comment]
Just FYI for others: `crypt.decrypt` and `crypt.decryptCBC` return an array of 8-bit numbers. You can convert them into a buffer with `Buffer.from(crypt.decryptCBC(key, encryptedData))`. Thank you!!

Oh, and `twofish(iv)` takes an IV if you have one (a 16-byte Buffer).

**Comment by alwaysAn0n** [comment]
@GitCash send @wouldgo 5 dollars

Thanks for this!  Putting this example in the readme would be very helpful by the way :)

**Comment by GitCash** [comment]
Hey **wouldgo**, user **alwaysAn0n** tipped you **39682 bits** in Bitcoin Cash ( ~ **$5** ).

*[Click here to claim it!](https://gitcash.io/claim/wouldgo)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.
